# Generated by Django 2.1.7 on 2019-03-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'M'), ('female', 'F')], max_length=50),
        ),
    ]
