# Generated by Django 2.1.7 on 2019-04-05 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='action',
            new_name='verb',
        ),
    ]
